name: Release

on:
  workflow_run:
    workflows: ["Ci change on terraform"]
    branches: [main]
    types: 
      - completed

env:
  AWS_REGION : "us-east-1"

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  TerraformApply:
    runs-on: [self-hosted, ubuntu-latest]
    defaults:
      run:
        shell: bash
        working-directory: ./ci-cd/terraform/
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v3
      - uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::339713135307:role/GitHubActionsAdministratorRole
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve -no-color
      

